name: ABI Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-abi:
    name: Release ABI
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build contracts
        run: forge build

      - name: Extract ABIs
        run: |
          mkdir -p abis
          jq '.abi' out/FilBeamOperator.sol/FilBeamOperator.json \
          > abis/FilBeamOperator.abi.json

      - name: Publish ABIs to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v6
        with:
          name: abis-${{ github.ref_name }}
          path: abis/**
